name: Sync Data
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Sync Data
        run: |
          pip3 install requests
          python sync.py
          git add db.json
          git config --global user.name 'QubitPi'
          git config --global user.email 'jack20191124@proton.me'
          git commit -am "Sync data"
          git push origin master
